name: thingsboard_app
description: Flutter ThingsBoard Mobile Application

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  thingsboard_client: 1.0.3
  intl: ^0.17.0
  flutter_secure_storage: ^6.0.0
  flutter_speed_dial: ^6.0.0
  cupertino_icons: ^1.0.2
  fluro: ^2.0.3
  flutter_svg: ^1.1.3
  auto_size_text: ^3.0.0-nullsafety.0
  infinite_scroll_pagination: ^3.0.1
  fading_edge_scrollview: ^3.0.0
  stream_transform: ^2.0.0
  flutter_inappwebview:
    git:
      url: https://github.com/rshrc/flutter_inappwebview
      ref: master
#  flutter_downloader: ^1.6.0
#  permission_handler: ^8.0.0+2
#  path_provider: ^2.0.2
  url_launcher: ^6.0.3
  image_picker: ^0.8.0
  mime: ^1.0.0
  logger: ^1.0.0
  qr_code_scanner: ^1.0.0
  device_info_plus: ^4.1.2
  geolocator: ^9.0.1
  material_design_icons_flutter: ^5.0.5955-rc.1
  package_info: ^2.0.2
  dart_jsonwebtoken: ^2.2.0
  crypto: ^3.0.1
  flutter_form_builder: ^7.0.0
  form_builder_validators: ^8.3.0
  universal_html: ^2.0.8
  universal_platform: ^1.0.0+1
  preload_page_view: ^0.1.6
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.10.0

flutter:
  uses-material-design: true
  assets:
     - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/thingsboard.png"
flutter_intl:
  enabled: true
